$content = Get-Content -Raw src\AcqShell.UI\MainWindow.axaml.cs
$content = $content -replace 'NativeModeRadioControl', 'NativeModeRadio'
$content = $content -replace 'TopologyStatusTextControl', 'TopologyStatusText'
$content = $content -replace 'SdkDirectoryTextBoxControl', 'SdkDirectoryTextBox'
$content = $content -replace 'ConfigDirectoryTextBoxControl', 'ConfigDirectoryTextBox'
$content = $content -replace 'MockDeviceCountTextBoxControl', 'MockDeviceCountTextBox'
$content = $content -replace 'MockChannelCountTextBoxControl', 'MockChannelCountTextBox'
$content = $content -replace 'SelectedDeviceTitleTextControl', 'SelectedDeviceText'
$content = $content -replace 'SelectedChannelsSummaryTextControl', 'SelectedChannelsSummaryText'
$content = $content -replace 'LogBoxControl', 'LogBox'
$content = $content -replace 'SdkStatusTextControl', 'SdkStatusText'
$content = $content -replace 'CallbackBlocksTextControl', 'CallbackBlocksText'
$content = $content -replace 'CallbackBytesTextControl', 'CallbackBytesText'
$content = $content -replace 'LastCallbackTextControl', 'LastCallbackText'
$content = $content -replace 'StartSdkValidationButtonControl', 'StartValidationBtn'
$content = $content -replace 'StopSdkValidationButtonControl', 'StopValidationBtn'
$content = $content -replace 'InitializeSdkButtonControl\.IsEnabled = true;', ''
$content = $content -replace 'Control\.Text', '.Text'
Set-Content "src\AcqShell.UI\MainWindow.axaml.cs" $content -Encoding UTF8
